version: '3.8'
services:
  sprinkled-db:
    image: postgres:14.5-alpine
    container_name: sprinkled-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sprinkled
    ports:
      - 5432:5432
    networks:
      - sprinkled-network
networks:
  sprinkled-network: