name: Backend Tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'sprinkled-backend/**'
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Navigate to sprinkled-backend
        run: cd sprinkled-backend

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test -- --passWithNoTests
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Navigate to sprinkled-backend
        run: cd sprinkled-backend

      - name: Install dependencies
        run: npm install

      - name: Run E2E Tests
        run: npm run test:e2e -- --passWithNoTests