name: Backend Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Unit Tests
        run: |
          cd sprinkled-backend
          npm install 
          npm run test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run E2E Tests
        run: |
          cd sprinkled-backend
          npm install 
          npm run test:e2e